"""Generate a redacted .env.example and scaffold a .env.schema from a .env."""

from __future__ import annotations

from .parser import ParsedEnv
from .schema import Schema
from .secrets import is_secret_key, match_known_patterns


def _placeholder_for(key: str, value: str) -> str:
    """Produce a safe placeholder for a value, redacting likely secrets."""
    if value == "":
        return ""
    if is_secret_key(key) or match_known_patterns(value) is not None:
        return f"your-{key.lower().replace('_', '-')}-here"
    # Numeric-looking values are safe to keep as a hint.
    if value.isdigit():
        return value
    if value.lower() in {"true", "false", "yes", "no", "on", "off"}:
        return value
    # Keep short, non-secret hints; redact long opaque strings.
    if len(value) <= 24 and " " not in value:
        return value
    return f"your-{key.lower().replace('_', '-')}-here"


def generate_example(env: ParsedEnv, *, schema: Schema | None = None) -> str:
    """Generate the text of a redacted ``.env.example`` from a parsed env file.

    Preserves key order, deduplicates (last wins), and redacts secret-looking
    values. If a schema is given, its descriptions are added as comments and
    ``secret``/``example`` hints are honored.
    """
    lines: list[str] = [
        "# Generated by envlint. Safe to commit: secret values are redacted.",
        "",
    ]
    seen: set[str] = set()
    # Iterate in file order but only emit the last assignment of each key.
    last_line_of: dict[str, int] = {e.key: e.line for e in env.entries}
    for e in env.entries:
        if e.line != last_line_of[e.key]:
            continue  # not the last assignment; skip the earlier duplicate
        if e.key in seen:
            continue
        seen.add(e.key)

        spec = schema.vars.get(e.key) if schema else None
        if spec and spec.description:
            lines.append(f"# {spec.description}")

        if spec and spec.example is not None:
            placeholder = spec.example
        elif spec and spec.secret is True:
            placeholder = f"your-{e.key.lower().replace('_', '-')}-here"
        elif spec and spec.secret is False:
            placeholder = e.value
        else:
            placeholder = _placeholder_for(e.key, e.value)

        lines.append(f"{e.key}={placeholder}")

    # Add schema-only keys (declared but not present in the env).
    if schema:
        for name, spec in schema.vars.items():
            if name in seen:
                continue
            if spec.description:
                lines.append(f"# {spec.description}")
            placeholder = (
                spec.example
                if spec.example is not None
                else (spec.default if spec.default is not None else "")
            )
            lines.append(f"{name}={placeholder}")

    return "\n".join(lines).rstrip() + "\n"


def generate_schema(env: ParsedEnv) -> str:
    """Scaffold a ``.env.schema`` (TOML) from an existing parsed env file."""
    lines: list[str] = [
        "# Generated by envlint. Edit required/type/allowed/secret as needed.",
        "",
        "[meta]",
        "complete = true",
        "",
    ]
    seen: set[str] = set()
    for e in env.entries:
        if e.key in seen:
            continue
        seen.add(e.key)

        secret = is_secret_key(e.key) or match_known_patterns(e.value) is not None
        guessed_type = _guess_type(e.value)

        lines.append(f"[vars.{e.key}]")
        lines.append("required = true")
        lines.append(f'type = "{guessed_type}"')
        if secret:
            lines.append("secret = true")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _guess_type(value: str) -> str:
    if value == "":
        return "string"
    if value.isdigit():
        n = int(value)
        return "port" if 0 <= n <= 65535 else "int"
    try:
        float(value)
        return "float"
    except ValueError:
        pass
    if value.lower() in {"true", "false", "yes", "no", "on", "off"}:
        return "bool"
    if value.startswith(("http://", "https://", "postgres://", "postgresql://", "mysql://", "redis://")):
        return "url"
    return "string"
